spring.application.name=individual-spring-websockets

spring.datasource.url=jdbc:oracle:thin:@//192.168.0.30:52244/dev191001db.proounce.com
spring.datasource.username=DUMMYDB
spring.datasource.password=DUMMYDB
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true